name: CI (compact)
env:
  BUILD_ARTIFACT: gigastore-artifact
  COVERAGE_ARTIFACT: gigastore-code-coverage
  COVERAGE_FILE: coverage.txt

on:
  push:
    branches: [ 'main' ]

  workflow_dispatch:

# Permissions (mainly for publishing on GH Pages)
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    outputs:
      repo_status: ${{ steps.visibility.outputs.status }}

    steps:
      # Audit
      - name: Checkout
        uses: actions/checkout@v5

      - name: Package audit
        run: npm audit

      # Lint
      # - name: Checkout
      #   uses: actions/checkout@v5

      - name: Install packages
        run: npm ci

      - name: Lint code
        run: npm run lint

      # Build
      # - name: Checkout
      #   uses: actions/checkout@v5

      # - name: Install packages
      #   run: npm ci

      - name: Build app
        run: npm run build

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.BUILD_ARTIFACT }}
      #     path: dist

      # Unit testing
      # - name: Checkout
      #   uses: actions/checkout@v5

      # - name: Install packages
      #   run: npm ci
      
      - name: Run unit tests
        run: npm test

      # Coverage
      # - name: Checkout
      #   uses: actions/checkout@v5

      # - name: Install packages
      #   run: npm ci
      
      - name: Check code coverage
        run: npm run coverage > ${{ env.COVERAGE_FILE }}

      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COVERAGE_ARTIFACT }}
          path: coverage.txt

      # Check if repo is public
      - name: Check if repo is public
        uses: credfeto/action-repo-visibility@v1.2.0
        id: visibility
      
      - run: |
          REPO_STATUS="${{ env.REPO_STATUS }}"
          echo "Repository status: $REPO_STATUS"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.repo_status == 'public'}}

    steps:
    - uses: actions/configure-pages@v5
    - uses: actions/checkout@v5
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-pages-artifact@v4
      with:
        path: dist
    - uses: actions/deploy-pages@v4
      id: deployment
